### PR TITLE
Fix compilation on macOS

### PR DESCRIPTION
**Pull request by robertjpayne**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description

macOS compilation on the `next` branch is currently broken regardless of how you configure it. These small tweaks fix it and also update a few dependencies for good will:

- Updates the min os deployment target to 10.9, this is necessary to be compatible with node 6.x due to issues with how c++ and c++11 work.
- Update curl to avoid compilation issues with SecureTransport and also ensure it doesn't attempt to compile http2 support even if libnghttp2 is on the system path
- Update openssl just for security reasons it should always be kept as up to date as possible
- Include icu4c headers because macOS doesn't ship with them

With these updates you can once again do `./configure --fetch all` and then `make -j8` and it compiles with no issues on macOS Sierra.

### CODE REVIEW

**Comment by srh** [comment]
Okay.  I like that SSL is upgraded.  I'd been putting that off...

Also, I'm glad that the min OS version is updated.  Personally I'd make it be 10.11.

Also, I thought v8 came with its own copy of ICU -- that's what we end up using.  So we fetch it as part of v8.  Is that no good anymore?

Anyway, regarding ICU, check out https://github.com/srh/rethinkdb/commit/94190efd1f4838e448e463c84a4ce697a1ed40ad -- we don't need ICU as a dependency, period.  I think that is the right solution for ICU build problems.

So I think you should drop your ICU changes, removing them from history so that cloning the repo doesn't take any longer, and cherry-pick my change that removes our dependency on ICU.

**Comment by robertjpayne** [comment]
@srh oh interesting regarding v8's ICU stuff, I'll have a look and see if we can re-use any headers.

Do you have a PR for removing ICU yet?

**Comment by robertjpayne** [comment]
@srh have another look, was able to get rid of ICU not sure why it constantly was giving me errors before.

I left deployment target as 10.9, I don't see any reason to go higher than what is necessary if it just works fine.

**Comment by robertjpayne** [comment]
Also one final change, darwinssl in curl crashes for some reason -- I can't see a reason not to just link to openssl that is fetched or on the system path?

**Comment by srh** [comment]
>  have another look, was able to get rid of ICU not sure why it constantly was giving me errors before.

You might want to `git clean -fxd` and rebuild again to make sure it really still works.

**Comment by srh** [comment]
Okay, `next` still compiles on macOS for me!  I just merged this into next as of f5d98a1e5dccf64771b84c332b18731bdce5e956.

Could you do v2.3.x now? :-)

But I forgot to test it out on Linux so I'll do that first before closing.

**Pull request closed without merging**
