### PR TITLE
Ruby unit specs

### PR DESCRIPTION
**Pull request by katafrakt**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/
### Description

Some time ago I was chatting on Slack with someone about adding specs to Ruby for faster feedback etc., making it the first step towards making the driver more Ruby-like. I actually haven't had much time to finish it, but I decided to post what I have for now. In case someone thinks it's useful, I can try to add more tests to have decent coverage.

Right now I covered things I was able to study and understand. Coverage according to `simple_cov` is about 51%.

I may have exaggerated with mocks here and there, but the way the code is written now makes it quite hard to write tests with high coverage without heavy mocking (at least to my knowledge).

So please, let me know if you think it's useful.

### CODE REVIEW

**Comment by AtnNn** [comment]
Thanks for writing and sharing these test.

I'm not qualified to review them right now, but I'll try to get someone to take a look at them.

**Comment by srh** [comment]
Hey @katafrakt -- I'll merge this if you say it's good to merge. You say you haven't finished this -- that means tests merely have incomplete coverage?  That would be fine.  It isn't, like, breaking stuff, right?

**Comment by katafrakt** [comment]
@srh Yes, coverage is not very high, but I can work on that later.

Just give me some time to check if it works with current `next` (should I merge it into this PR?) and add some info to README, please.

**Comment by srh** [comment]
Yeah, you can merge it into this PR i.e. put it on your branch and the PR gets updated.

**Comment by katafrakt** [comment]
Ok, my problem is that current `next` branch does not compile neither on Mac, nor on Linux (with different errors though). Do you perhaps know if this is a known issue?

Mac error:

```
    [244/429] CC build/release_clang/obj/extproc/js_job.o
In file included from src/extproc/js_job.cc:4:
./build/external/v8_3.30.33.16-patched/include/v8.h:6267:54: error: 'CreateHandle' is a protected member of
      'v8::HandleScope'
  return Handle<T>(reinterpret_cast<T*>(HandleScope::CreateHandle(
                                        ~~~~~~~~~~~~~^~~~~~~~~~~~
./build/external/v8_3.30.33.16-patched/include/v8.h:836:29: note: declared protected here
  static internal::Object** CreateHandle(internal::Isolate* isolate,
                            ^
1 error generated.
make[1]: *** [build/release_clang/obj/extproc/js_job.o] Error 1
make: *** [make] Error 2
```

**Comment by srh** [comment]
It depends which Linux you have.  But on macOS the branch `next` does compile for me (I'm doing it right now).  Your error there looks like one which was fixed?  Or one which I saw.  Let me make clean and compile again...

**Comment by katafrakt** [comment]
Linux (Arch) error is:

```
    [1/267] CC build/release/obj/client_protocol/server.o
src/client_protocol/server.cc: In member function ‘size_t http_conn_cache_t::sha_hasher_t::operator()(const conn_key_t&) const’:
src/client_protocol/server.cc:177:16: error: aggregate ‘EVP_MD_CTX c’ has incomplete type and cannot be defined
     EVP_MD_CTX c;
                ^
make[1]: *** [src/build.mk:381: build/release/obj/client_protocol/server.o] Error 1
make: *** [Makefile:53: make] Error 2
```

**Comment by srh** [comment]
That's an SSL version compatibility issue with your ssl devel package (I think?).  [cries internally]  Try --fetch options to fix that.

**Comment by srh** [comment]
For building on macOS I got it working now, having merged 2c1e19cb3d32ea9feb669af6034c5960d0f87dc4.

The reason it had worked for me before is that I'd made that change in a branch, tested it out, and then switched back to other branches -- and make clean doesn't undo patching operations on external dependencies, the result being that the build succeeded.

In the long run I want to replace v8 with Duktape and vendorize the shiznit out of these external dependencies.

**Comment by katafrakt** [comment]
Ok, specs checked - they work with current `next` branch. And Info to README was added. From my side - it's good to merge.

**Comment by srh** [comment]
Okay, thank you.  Your commits are in next as of ed7dbdd9e86e7c59570a3189a9f0545f236191e8.

**Pull request merged**
