### PR TITLE
Incorporate changes from atnnn/rethinkdb-webui

### PR DESCRIPTION
**Pull request by AtnNn**
I converted the web UI into a standalone app in https://github.com/AtnNn/rethinkdb-webui

I'm porting some of the changes back here:

* In `admin/`, running `node serve.js` will launch a stand-alone web UI
* All static assets are moved to `assets/`
* Coffee, handlebars and less sources are moved to `src/`
* Got rid of gulp and shortened the build script by 85%

### CODE REVIEW

**Comment by deontologician** [comment]
Oh! Just saw this! Sorry, I will review

**Comment by deontologician** [comment]
So I looked over it, definitely nicer to have removed a lot of gulp. Two things that existed before that were nice for developing on the webui we're the ability to rebuild on source changes (check out [watchify](https://github.com/substack/watchify)) and the build time were significantly reduced due to gulp pipelining. I haven't run this so I don't know what the speed is now, but your bash-foo is way better than mine so maybe the way it was building in make before was really inefficient and this way is fine.

Also, the instructions for creating a bundled build are a bit  terse I think. I am not sure if "replace npm with make" is clear enough, it might help to add an example

LGTM overall, this is a long time coming and I'm really glad someone finally did it! I'll leave it up to your excellent judgement on the remaining points

**Comment by AtnNn** [comment]
Thanks for the suggestions. I added watching and improved the README.

On my machine, this branch builds the web UI in half the time as the old gulp script.

**Comment by deontologician** [comment]
:+1:

**Comment by AtnNn** [comment]
merged into next as 3710301

**Comment by srh** [comment]
This doesn't build on my machine.  Debian Jessie.

A fresh build gets all the way up to

```
   [607/616] COFFEE build/drivers/javascript/coffee/util.js
    [608/616] CP ./build/packages/js
    [609/616] CP build/packages/js/node_modules/bluebird
    [610/616] BROWSERIFY build/drivers/javascript/rethinkdb.js
    [611/616] CP build/web_assets/rethinkdb.js
    [612/616] COFFEE build/web_assets/cluster.js
    [613/616] LESSC build/web_assets/cluster.css
/usr/bin/env: node: No such file or directory

Full error log: ./build/web_assets_js.log
admin/build.mk:27: recipe for target 'build/web_assets/cluster.js' failed
make[1]: *** [build/web_assets/cluster.js] Error 1
/usr/bin/env: node: No such file or directory

Full error log: ./build/web_assets_css.log
admin/build.mk:31: recipe for target 'build/web_assets/cluster.css' failed
make[1]: *** [build/web_assets/cluster.css] Error 1
make[1]: Target 'default-goal' not remade because of errors.
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
```

**Pull request closed without merging**
