### PR TITLE
don't persist stale env_t* in ordered unions

### LINKED ISSUE #6139: Segfault in `thread_pool.cc`
One of our nodes just did this:

```
2016-10-10T15:50:16.549054705 1504844.600086s error: Error in src/arch/runtime/thread_pool.cc at line 367:
2016-10-10T15:50:16.549118950 1504844.600146s error: Segmentation fault from reading the address 0x7efea8329910.
2016-10-10T15:50:16.549136370 1504844.600163s error: Backtrace:
2016-10-10T15:50:36.303983568 1504864.355013s error: Mon Oct 10 15:50:16 2016\n\n1 [0xabda80]: backtrace_t::backtrace_t() at ??:?\n2 [0xabde13]: format_backtrace(bool) at ??:?\n3 [0xd41b8d]: report_fatal_error(char const*, int, char const*, ...) at ??:?\n4 [0x9d9fe3]: linux_thread_pool_t::fatal_signal_handler(int, siginfo_t*, void*) at ??:?\n5 [0x7f1e71e11330]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x10330) [0x7f1e71e11330] at 0x7f1e71e11330 (/lib/x86_64-linux-gnu/libpthread.so.0)\n6 [0x7efea8329910]: [0x7efea8329910] at 0x7efea8329910 ()
2016-10-10T15:50:36.304056053 1504864.355083s error: Exiting.
```

### PR DESCRIPTION
**Pull request by AtnNn**
Possibly fixes #6139

### CODE REVIEW

**Comment by marshall007** [comment]
@AtnNn awesome! I'll compile a binary and test this first thing tomorrow.

**Comment by marshall007** [comment]
I've confirmed I was also no longer able to reproduce the segfault with this patch, so 👍 from me.

@thelinuxlich I don't know how soon we'll have the infrastructure in place to release official binaries again, but this patch likely resolves your issue if you wanna compile and give it a try.

**Comment by srh** [comment]
Another place that puts an `env_t *` in a field is get_selection_t and extreme_selection_t.  These end up getting put into a val_t.  Is there any chance that a val_t could escape its env_t's lifetime?  In other places it seems used mostly for short-lifetime objects like static_visitor.  (But one sketchy-looking place generally speaking is in datum_replacer_t.)

**Comment by AtnNn** [comment]
It also looks to me like `val_t` don't escape their `env_t`'s lifetime. But the result of `val_t::as_seq()` sometimes does.

**Comment by srh** [comment]
LGTM.

**Pull request merged**
