### PR TITLE
Fix uses of run_options/runOptions in _export.py.

### PR DESCRIPTION
**Pull request by srh**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
Thanks to my merging of 3b29933aa033e6b871ae43418c62005b113f39c1 by @rayrase the export script was now broken, using `runOptions`.  This fixes the export script.

I also will cherry-pick 3b29933aa and then this fix onto v2.4.x.

### CODE REVIEW

**Comment by marshall007** [comment]
LGTM

**Comment by rayrase** [comment]
First open source contribution so I was going for something easy. Still managed to screw it up though. Sorry about that.

**Comment by srh** [comment]
Ah but it was a user's fault for using the unstable branch... and the original developer's fault for making a non-Pythonic API.

**Comment by srh** [comment]
In next as of dc595620ed32c79ddb25ff8ca18882fa69b35f8d.

**Comment by rayrase** [comment]
Thanks @srh. That helps. I'll make sure to do a better job next time. Have a great day.

**Pull request closed without merging**
