### PR TITLE
Ruby: Allow grouped data to be parsed for rql types

### PR DESCRIPTION
**Pull request by nviennot**

### CODE REVIEW

**Comment by danielmewes** [comment]
Thank you @nviennot .

@mlucy could you review please?

**Comment by mlucy** [comment]
This looks good to me, merging.  (@nviennot has signed the CLA before.)

**Comment by nviennot** [comment]
:heart:

**Comment by danielmewes** [comment]
@nviennot Do you currently need this (e.g. for nobrainer)? We could cherry-pick it into `v2.2.x` and release a driver update before the 2.3 release.

**Comment by nviennot** [comment]
I don't, @francocorreasosa was the one experiencing the issue and posted it on nobrainer, but was unrelated to nobrainer. He already found a workaround, so no hurry.
Thank you though

**Comment by francocorreasosa** [comment]
@nviennot 👏👏👏👏👏

**Pull request merged**
