### PR TITLE
fix: patch for rethinkdb 2.4.1 osx build

### PR DESCRIPTION
**Pull request by chenrui333**
👋  adding a patch for osx builds (see https://github.com/Homebrew/homebrew-core/pull/59643 and https://github.com/Homebrew/homebrew-core/pull/67782)

### CODE REVIEW

**Comment by srh** [comment]
Thank you.

It looks like it'll work without updating the vendored boost version.

That's a good thing, because the date type is based on the boost library, and I'm not keen on changing how that gets built (though I'm considering that probably we should *always* vendor it for that reason).

Anyway, this patch seems like it'll drop in and build.  I'll test it out first and then merge it.

**Comment by chenrui333** [comment]
Thanks @srh!

**Comment by stakach** [comment]
any chance of movement on this one @srh ?

**Comment by srh** [comment]
@stakach Yes.

Also, cherry-picked into v2.4.x with
d7e2706bf28bda2ef88666819173acd249a8a96e

**Pull request merged**
