### PR TITLE
Support almost all types of data conversion from db to java, include nested List/Array

### PR DESCRIPTION
**Pull request by QianJin2013**
This is almost same as #5484, just resolved conflict.

Hope this easy to review and merge.

### CODE REVIEW

**Comment by QianJin2013** [comment]
sorry i forgot to change commit author name, it is too short ("q") now.

**Comment by danielmewes** [comment]
Thanks for updating the branch @QianJin2013 .

**Comment by rgv151** [comment]
when will this PR get merged?

**Comment by deontologician** [comment]
Hey @rgv151, I've been busy with the Horizon release recently, but now that things have slowed down I can check this out. Thanks for the poke :)

**Comment by mcjp78** [comment]
Irs been 5 months so bumpy

**Comment by mcjp78** [comment]
@danielmewes

**Comment by marshall007** [comment]
LGTM

@QianJin2013 would you mind rebasing this on top of `next` again so we can cleanup the conflicts? We're going to try to get this merged as soon as we can.

**Comment by bchavez** [comment]
JM2C, I would probably look into going in a different direction by changing the default Java serializer to Jackson/Gson going forward. See: https://github.com/rethinkdb/rethinkdb/issues/5128

It appears there is a lot of special case type handling in this PR. I think, all this special-case code could be better handled by a more convenient JSON serializer for Java. Having a look at [`net/Util.java`](https://github.com/sjitech/rethinkdb/blob/ad253bc42a9799e4f7f821e36902d04ac2015684/drivers/java/src/main/java/com/rethinkdb/net/Util.java) there's a lot of code just for trying to select the right constructor for a POJO and plucking off special casts to/from Java native types.

IMHO, the problem, as I see it, with handling explicit special-case type conversion inside the driver like this is that it leads to a very rigid design. Someone will always have some reason to change the way the driver is handling a specific type, for whatever reason, and then we've gifted ourselves a maintenance headache trying to handle everyone's special case.

I think, the better approach toward maintainability is to push all this special-case type conversion outside the purvue of the driver. But how does one achieve such greatness? Well... if Jackson/Gson work anything like `Newtonsoft` in C# land there are serialization/deserialization extension APIs that can be implemented to output low-level wire JSON. A proper JSON implementation using *something* like [Gson's `TypeAdapter`s](http://static.javadoc.io/com.google.code.gson/gson/2.7/com/google/gson/TypeAdapter.html) could enable native Java type to `$reql_type$` pseudo type conversions without having to go crazy with `if-else` checks everywhere inside the driver. And, developer issues that require special case-conversions, for whatever reason, now become issues of customizing the Jackson/Gson serializer and not issues at odds with the **RethinkDB Java** driver itself.

At least, this was the approach I took with the `bchavez/C#` driver and it's been working out pretty well. Relatively low bug count and pretty much breeze to maintain (*alright, probably jinxed it now*). Type conversions, enums and all that get handled by `Newtonsoft`; so storing enums as `string` or `int` representations wit annotation/attributes, it don't matter, err'body doing their own thing with da JSON. Whatever people want.

:fallen_leaf: :leaves: [**Distance - Falling (ft Alys Be)**](https://www.youtube.com/watch?v=WIfwIv4wNCE)

**Comment by deontologician** [comment]
:+1: for GSON/ Jackson. What initially seemed like a small addition of a
few built in coercions morphed into a maintenance black hole. For obvious
reasons that's a bad idea, so it's probably worth trying to go all the way
with a proper serializer

**Comment by mcjp78** [comment]
Would that just mean replacing all serialization with Jackson or GSON? From what I can see there is a lot besides that which would need to be changed.

**Comment by QianJin2013** [comment]
@marshall007 OK, i am starting rebase code now. 

Be aware that the way i solved the conversion problem was an ad-hoc & just-work way, not perfect. 
Some rare case logic are low efficiency(such as  many type .toString() then get parsed) and
the handling of generic list was a little ugly.

**Comment by deontologician** [comment]
@mcjp78 what else do you think would need to be changed?

**Comment by mcjp78** [comment]
@deontologician by that I meant code that needs to be changed to support Jackson.

**Comment by mcjp78** [comment]
I believe the net/util and ast/util for a proper serializer (may be wrong)

**Comment by QianJin2013** [comment]
hi, everyone. I'v done rebase. Now no conflicts.

**Comment by mcjp78** [comment]
While this currently may be a a maintenance issue, it will work in the interim before the driver is set up to work with Jackson. I vote for a merge, it is git so it can be undone.

**Comment by PeterKnego** [comment]
Please take a look at rethindb-java-orm: https://github.com/DevScore/rethinkdb-java-orm

It's a full-featured lightweight ORM built on top of Java driver.

**Comment by mcjp78** [comment]
@PeterKnego make connection the args so cert files are supported. Also, what is that for.

**Comment by PeterKnego** [comment]
It's a Java ORM (object-relational-mapping) built on top of RethinkDB Java driver. Unfortunately there are no docs, but it's been used in production. See the tests to see what it can do.

It's much more full-featured then built-in properties-to-object mapper.

**Comment by mcjp78** [comment]
@PeterKnego i don't fully understand the use of this... Do you have any sample apps or something?

**Comment by PeterKnego** [comment]
@mcjp78Please check out  the [unit tests](https://github.com/DevScore/rethinkdb-java-orm/tree/master/src/test/java/com/rethinkdb/orm). Here are some [example annotated entity classes](https://github.com/DevScore/rethinkdb-java-orm/tree/master/src/test/java/com/rethinkdb/orm/entities).

**Comment by mcjp78** [comment]
Take a look at #6157 . It converts rethinkdb to using Jackson and therefore supports enums/most datatypes :)

**Comment by marshall007** [comment]
@mcjp78 nice work on #6157! As @deontologician and @bchavez mentioned this is definitely the better long term solution. I'm glad it was relatively straight forward to implement.

**Comment by mcjp78** [comment]
ty

**Comment by mcjp78** [comment]
@QianJin2013 Ty tho for bringing this to light

**Comment by QianJin2013** [comment]
I am regret to here that RethinkDb is shutting down.
So many great works.

OK, it's been a long time since i made this just-work patch, i'v already forgot it.
In fact, i do not like such a bunch of code to just a type conversion.

@mcjp78 I am glad to here you contributed a more simple way to do the conversion.

**Comment by AtnNn** [comment]
Closing in favor of #6157. Thanks for your contributions.

**Pull request closed without merging**
