### PR TITLE
Export hidden cursor classes

### PR DESCRIPTION
**Pull request by ralphholzmann**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
In building a new Node.js based model library for RethinkDB, we've found that it can sometimes be beneficial to be able to test what class of response is being returned from `rethinkdb`. This commit exports all of the cursor classes (under `r.net.cursors`) so we'll be able to do things such as

```js
if (result instanceof ArrayResult) {
  // something
}
```

### CODE REVIEW

**Comment by srh** [comment]
What are you using this for?  Is it to see whether a result is an array (which, I presume, contains all returned data and doesn't need to fetch more) or not?

This is an API change so we don't want to expose driver internals unnecessarily.

**Comment by srh** [comment]
Hey @ralphholzmann, Can you please confirm whether what you want is specifically to see if the result is an array or if it's a cursor?  That you don't specifically want more?

**Comment by ralphholzmann** [comment]
Heyo -- sorry for the late reply here. Yes, that's essentially what I need, some way to differentiate.

**Comment by srh** [comment]
I'll make an issue before closing if not a patch that sees if a cursor is an array vs stream.

**Pull request closed without merging**
