### PR TITLE
Bind .run's callback to current domain(issue #4475).

### PR DESCRIPTION
**Pull request by svarogg**
In relation to https://github.com/rethinkdb/rethinkdb/issues/4475

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the pull request @svarogg !
If you haven't done so yet, would you mind signing our CLA? You can do so at http://rethinkdb.com/community/cla/

@deontologician do you think this is the right way to fix this? Or should we wait for a fix in Bluebird? https://github.com/rethinkdb/rethinkdb/issues/4475

**Comment by svarogg** [comment]
@danielmewes Yeah, I have signed the CLA already.

**Comment by deontologician** [comment]
Ok, so I've read up on domains now. It looks like this should be fine, but given that the bluebird issue is being actively worked on, let's give see if they fix it soon. If not we can merge this. I think ideally upstream fixing it would be better

**Comment by deontologician** [comment]
Also, if we do go with this, we should add some tests. I extended @svarogg 's example a bit here, showing it fails with callbacks and promises:

https://gist.github.com/deontologician/89f0306a804d9062af65

**Comment by svarogg** [comment]
This fix is more or less the thing the guys at mongodb did.

**Comment by deontologician** [comment]
Since bluebird has fixed this (see https://github.com/rethinkdb/rethinkdb/issues/4475#issuecomment-118994291) I'm closing this PR in favor of bumping the bluebird version. Thanks @svarogg for bringing this issue to our attention

**Pull request closed without merging**
