### PR TITLE
Add v8 patch for Clang 9.0

### PR DESCRIPTION
**Pull request by robertjpayne**
- [X] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

Adds v8 patch to future proof compilation when Xcode 9 ships with Clang 9.0 in a month or so

### CODE REVIEW

**Comment by robertjpayne** [comment]
The only thing I could think of that is bad with this is `--without-nghttp2` on the curl configure. If you have system nghttp2 installed it'll take advantage of it and use http2.

But given that RethinkDB runs all HTTP calls in subprocesses I'm not sure we'd gain any benefit here? Does it keep the process alive to the point where using a single TCP connection for multiple requests would even work?

**Comment by robertjpayne** [comment]
I have no idea why GitHub is showing diffs the two cherry picked commits that @srh already merged in #6399

**Comment by robertjpayne** [comment]
If we commit this and then backport it and  #6399 into v2.4.x we can compile 2.4.x on macOS!

**Comment by srh** [comment]
This looks good to me -- I say merge it.

**Comment by srh** [comment]
This looks good to me -- I say merge it.

**Comment by srh** [comment]
In next as of 88c1a8508504127391ff5df49128c30ae9d6b164.  Still needs backporting into v2.4.x as mentioned above.

**Comment by srh** [comment]
Backported to v2.4.x in 07ae49f1c8c6d24c85c3d3ea9601e061ebe010df and v2.4.x compiles on macOS.

Thank you!

**Pull request closed without merging**
