### PR TITLE
Implemented the feature to import from Yaml files on #4864

### PR DESCRIPTION
**Pull request by brunoalano**

### CODE REVIEW

**Comment by larkost** [comment]
@brunoalano: Thanks for starting the work on this, it will be nice to get your changes in once we make it through the process. Have you already signed our [contributor agreement](http://rethinkdb.com/community/cla/)?

**Comment by larkost** [comment]
@brunoalano: pinging to see if you are still interested in making the changes to submit this?

**Comment by brunoalano** [comment]
@larkost Sorry, I'm busy these times. In 2 weeks I can proceed

**Comment by srh** [comment]
I don't think we want this change because it adds a dependency and makes more sense as an external library.  Also, no CLA anyway.  Closing.

**Pull request closed without merging**
