### PR TITLE
Java Driver: Fixes #5841. Reset handshake!

### LINKED ISSUE #5841: Java Driver: New handshake broke `.reconnect()`
I was noticing some weird behavior in the C# driver with the connection pooling code. I noticed, when `Connection.Close()` is called, any attempts to `.Reconnect()`, the reconnect always fails even if the TCP physical socket connection was okay.

I think this is due some internal `Handshake` state that is not being `.reset()` when the reconnect is attempted.

##### `Handshake.java`
```
    public Handshake(String username, String password) {
        this.username = username;
        this.password = password;
        this.state = new InitialState(username, password);
    }

    public void reset() {
        this.state = new InitialState(this.username, this.password);
    }
```

And there's some code here that kinda [sits here](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/SocketWrapper.java#L82) except, on the 2nd time around, the `Handshake` was finished from the 1st attempt. :8ball:
```
void connect(Handshake handshake){
....
            while(!handshake.isFinished()) {
                if (toWrite.isPresent()) {
                    write(toWrite.get());
                }
                String serverMsg = readNullTerminatedString(deadline);
                toWrite = handshake.nextMessage(serverMsg);
            }
....
}
```
So, the reconnect results in no re-authentication...

`Handshake.reset()` is nowhere to be found in [`Connection.java`](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java) or in [`SocketWrapper.java`](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/SocketWrapper.java)

The *pythin* :snake: code seems to `Handshake.reset()` in something like [`ConnectionInstance`](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/asyncio_net/net_asyncio.py#L154)?

My fix in the C# driver is in [`SocketWrapper.cs`](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/SocketWrapper.cs#L42) / [UnitTest](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver.Tests/Network/ConnectionTest.cs#L70). ***I think*** this would be the right place for the reset. Also, seems to have resolved my `.Reconnect` issue in the C# driver. :smile_cat: 

Let me knoooooooo what your thinking and I'll submit a PR for ya.

Muchas gracias,
Brian

:thought_balloon: :mag: [***"I want to know... what you're thinking..."***](https://www.youtube.com/watch?v=ijAYN9zVnwg)

### PR DESCRIPTION
**Pull request by bchavez**
### Description
Fixes #5841. [Ported from the C# driver.](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/SocketWrapper.cs#L42)

:car: :blue_car: [***"Let the good times roll..."***](https://www.youtube.com/watch?v=7BDBzgHXf64)

### CODE REVIEW

**Comment by deontologician** [comment]
Looks good to me too. Thanks again Brian :)

**Comment by deontologician** [comment]
@danielmewes I'm assuming I should backport this?

**Comment by danielmewes** [comment]
@deontologician :+1:

**Comment by deontologician** [comment]
ok, ported

**Comment by pires** [comment]
@deontologician is this gonna be available as 2.3.4?

**Comment by deontologician** [comment]
I'm not sure the exact version, it'll be whatever the current patch version is +1

**Comment by pires** [comment]
@deontologician current version for Java driver is 2.3.2.

**Pull request merged**
