### PR TITLE
2.0.4 release notes

### PR DESCRIPTION
**Pull request by danielmewes**
@mglukhovsky @AtnNn could you review please?

### CODE REVIEW

**Comment by danielmewes** [comment]
I forgot including https://github.com/rethinkdb/rethinkdb/issues/4242 , which will also be part of the release.

**Comment by AtnNn** [comment]
Looks good to me.

**Comment by danielmewes** [comment]
I added the description of #4242.
@mglukhovsky would you mind taking a look at the release notes as well?

**Comment by mglukhovsky** [comment]
Looks great!

**Comment by danielmewes** [comment]
Thanks! Merged.

**Pull request merged**
