### PR TITLE
refactor class check in ruby driver

### PR DESCRIPTION
**Pull request by aderyabin**
Link to style guide - https://github.com/bbatsov/ruby-style-guide#no-case-equality

### CODE REVIEW

**Comment by mlucy** [comment]
This also looks good to me.  Thanks for taking the time to clean stuff up!

**Comment by mlucy** [comment]
(@aderyabin mentioned he signed our CLA in https://github.com/rethinkdb/rethinkdb/pull/3900.)

**Comment by aderyabin** [comment]
@mlucy I think you need service that validates committer on CLA like passed test on Travis https://yadi.sk/i/OA5eUMIrf6Bgb

**Comment by mlucy** [comment]
That would be pretty cool.  Any thoughts on that @mglukhovsky?

**Comment by mglukhovsky** [comment]
@aderyabin: that's a great idea, I think I can whip up something like that easily.

I'm in the middle of several projects, but I'd like to put that next on the list, since it'll be relatively easy to do and will make everyone's life easier.

**Comment by aderyabin** [comment]
@mglukhovsky I'm ready to help with this github service.

**Comment by mglukhovsky** [comment]
@aderyabin -- thanks! We keep our list of contributors on an external service, and I'm not certain if there's an API, so it'll take some coordination on my end. I'll ping you once I sort out the details.

**Pull request merged**
