### PR TITLE
Add missing return keyword in TermBase constructor

### PR DESCRIPTION
**Pull request by mikemintz**
See https://github.com/rethinkdb/rethinkdb/issues/162 and https://github.com/rethinkdb/rethinkdb/pull/5067 for context.

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks. So the one we merged had the `return` in the `if` case, but didn't have it in the `else` case?

Is this causing an actual problem that you're running into? Just trying to understand how to test this...

**Comment by mikemintz** [comment]
Sorry for the confusion, I wasn't even thinking about the `if` case just now because it's skipped for IE10.

But yes, that's right. This change only affects IE10, not the tests (which have `__proto__`). I tested it manually by adding that `return` keyword in the `ast.js` under node_modules for a test app. As long as the output JS code contains `return this;` in the `else` clause, it'll work as expected.

**Comment by danielmewes** [comment]
Gotcha. Merging this.

**Comment by danielmewes** [comment]
It will ship with RethinkDB 2.2.6.

**Pull request merged**
