### PR TITLE
Added version var to Python Driver 

### PR DESCRIPTION
**Pull request by yograterol**
QuickFix https://github.com/rethinkdb/rethinkdb/issues/3100

This change does not has third party requirements.

### CODE REVIEW

**Comment by yograterol** [comment]
@AtnNn this is the new PR, with my proposal.

**Comment by AtnNn** [comment]
Thanks for making the changes.

Why did you use both `execfile` and `exec`? Is it a Python 2/3 issue?

**Comment by yograterol** [comment]
@AtnNn yep, https://docs.python.org/3.3/whatsnew/3.0.html?highlight=execfile#builtins

**Comment by AtnNn** [comment]
Good to know. Perhaps we can even drop `execfile` and use `exec` for both Python 2 and 3.

I'll merge this patch as soon as I get around to testing it successfully.

**Comment by yograterol** [comment]
@AtnNn Done!

**Comment by AtnNn** [comment]
This seems to work fine on Python 2.6, 2.7 and 3.3.

```
>>> import rethinkdb as r
>>> r.__version__
'1.16.0-0'
```

Thanks @yograterol. I see you've already signed the CLA. Merging.

**Pull request merged**
