### PR TITLE
Update Bluebird and reformat JSON in drivers/javascript

### PR DESCRIPTION
**Pull request by iamclaytonray**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
<Please fill in the description of your pull request here. Thank you for your contribution!>
Not sure how/why the `package.json` and `.groc.json` became so poorly formatted but I reformatted them and update `bluebird` to the latest and greatest. Oh, and I added `node_modules/` to the `.gitignore`

### CODE REVIEW

**Comment by srh** [comment]
Thank you for the changes. I'm confused though. I've never had node_modules appear as an untracked directory before. What are you doing to make that appear?  Also, what is the yarn.lock file for?

**Comment by iamclaytonray** [comment]
When someone has the repo on their local machine, they can just run `yarn` or `npm install` in that directory to grab the `node_modules`. This takes bloat away from Git and a few other benefits. It's rare when I actually see a repo not ignore it.

As far a `yarn.lock` goes, both yarn and npm both lock deps to ensure specifics about each dep, that you can't get in the package.json. Just makes things a bit more consistent. <a href="https://yarnpkg.com/lang/en/docs/yarn-lock/">Here's some more info on yarn.lock</a>

**Comment by iamclaytonray** [comment]
I can update the readme so future developers know what to do, if you'd like? Most JS devs already know what to do so it's not going out of convention but adding a "Getting Started" to the readme can't hurt either.

**Comment by srh** [comment]
So what you're talking about is if somebody runs `cd drivers/javascript; npm install`?

Do the two commits I added at https://github.com/srh/rethinkdb/commits/pull6525 seem reasonable to you?

Sorry for the slowness -- your change is mergeable (I'll take your word on the yarn stuff) and I'm just holding it hostage to get you to answer my questions :-)

**Comment by iamclaytonray** [comment]
Yes. So, when you run `npm install` or `yarn add`, npm/yarn will install whatever dep you specify and then install what deps that package uses. As far as yarn goes, npm v5+ now does the same thing with locking deps. For npm, it outputs a `package-lock.json`. For yarn, it outputs a `yarn.lock`.

**Comment by iamclaytonray** [comment]
Either PR is fine. They both do the same thing, pretty much. I'd still keep my refactor of `package.json` because it's super messy at this point. I'd also add that node_modules should be ignored globally as well.

I'm curious... Right now, there aren't any `node_modules` under the entire repo but you haven't globally ignored them. Have you guys just been deleting `node_modules` for each commit that you've working with JS?

**Comment by iamclaytonray** [comment]
Here's a good reference. 

<a href="https://github.com/mongodb/node-mongodb-native">MongoDB JS Driver</a>

**Comment by srh** [comment]
The driver gets copied to build/ and built there, so its node_modules directory is already ignored.

**Comment by iamclaytonray** [comment]
Cool! Well, I'll let you decide what you'd like to do 😄

**Comment by srh** [comment]
Alright, this is in `next` as of 5ca285443c9a5962828f62f6a35767af25fa3b4d.

**Pull request closed without merging**
