### PR TITLE
JS: Avoid side effects on object passed to r.connect

### PR DESCRIPTION
**Pull request by srh**
(The true author of this is @marshall007 in a [comment](https://github.com/rethinkdb/rethinkdb/pull/6135#issuecomment-307544187) in PR 6135.)

@marshall007 Could you please agree to the CLA for this change?  Since you're the author.

### CODE REVIEW

**Comment by marshall007** [comment]
👍

**Comment by srh** [comment]
@marshall007 Do you agree to the CLA at https://rethinkdb.com/cla/ ?

**Comment by srh** [comment]
Did you sign the new CLA?

**Comment by marshall007** [comment]
I believe so, but I just signed it again just in case.

**Comment by srh** [comment]
Thanks.
In v2.4.x as of 472019956768b8bbd07f66bb3bd5180e599bccdc.
In next as of 1834ca958b871927f0cf6adfe65d8e90af0ad1c2.

**Pull request closed without merging**
