### PR TITLE
Added a test for the '.filter(...)' function in the Java driver

### PR DESCRIPTION
**Pull request by igorlukanin**
I wrote this test as a tiny workaround to the lack of Java driver docs mentioned [here](https://github.com/rethinkdb/rethinkdb/issues/3930#issuecomment-154913718). I hope it's worth adding to the driver code base.

I think that @deontologician is the appropriate assignee for this PR.

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the PR @igorlukanin .

We actually have some tests that are automatically generated from the yaml files in `test/rql_test/src`, including a wide variety of `filter` tests. @deontologician can tell you how to run them.

@deontologician Do you think it makes sense to add a manual test like this anyway? I think it's probably not that useful, given that we already have tests for this.
I can see a use as a code example, but we will have full API documentation for the Java driver including `filter` examples done very soon.

**Comment by deontologician** [comment]
I don't think we have any autogenerated filter tests currently since they likely use r.row somewhere in the file

**Comment by danielmewes** [comment]
Oh I see. I didn't consider that.

**Comment by deontologician** [comment]
I'll merge it, since it can't hurt until the other tests are convertible. I think ultimately the RethinkDBTest file may end up the beginning of the connection-like tests

**Pull request merged**
