### PR TITLE
Adding slack to readme

### PR DESCRIPTION
**Pull request by coffeemug**
Adding slack info to the readme.

@dalanmiller -- could you review?

### CODE REVIEW

**Comment by mglukhovsky** [comment]
Do we want to recommend both Slack and Gitter? It seems a bit confusing to
have three.

**Comment by dalanmiller** [comment]
I think until @deontologician completes the Slack Bridge Bot we should still have IRC, Gitter, and Slack. 

I still think the Gitter experience is better than a "Slack Community" organization because it only requires Github oauth and also doesn't devolve into channel-pocalypse.

**Comment by coffeemug** [comment]
Personally I would strongly prefer dropping Gitter entirely, but if @dalanmiller wants to keep it I'm cool with that too.

**Comment by deontologician** [comment]
We could add gitter to the bridge bot too theoretically

**Comment by mglukhovsky** [comment]
@deontologician: what is this about a bridge bot? sameroom.io exists, but I wasn't a huge fan of the experience when testing it.

I believe Gitter provides a slightly worse experience, and agree with @coffeemug. I'd remove it from the readme, but keep it active for those who prefer it.

**Comment by mglukhovsky** [comment]
@dalanmiller if you'd like to keep it, that's fine. I just feel like the readme is a bit too confusing by not clearly declaring one as the primary -- and I'd prefer it be Slack.

**Comment by deontologician** [comment]
@mglukhovsky what didn't you like about sameroom specifically? The main thing I wanted to do with the bridge bot was coalesce chat. It seems pretty easy since they all have a chat api

**Comment by mglukhovsky** [comment]
@deontologician: I tested it with IRC, and it dropped some messages (which may have been a temporary bug) and provided confusing output. I don't know if Gitter <-> Slack integration is better due to the API.

**Comment by deontologician** [comment]
@mglukhovsky how long ago was that? We could try again or I could build this bot. My goal is to not have to check 3 different chat channels + github issues

**Comment by mglukhovsky** [comment]
@deontologician: about two months ago, we can give it another go if you'd like to try it out.

**Comment by dalanmiller** [comment]
screenshot 2015-10-09 14 51 58

Cool @coffeemug ?

**Comment by mglukhovsky** [comment]
@dalanmiller Is there any way to adjust the vertical alignment of the SVG badge?

**Comment by coffeemug** [comment]
:+1:

**Comment by dalanmiller** [comment]
You lucked out @mglukhovsky - `valign` [is on the approved whitelist](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L74)

screenshot 2015-10-09 15 18 52

**Pull request merged**
