### PR TITLE
Adding __aiter__ and __anext__ to Python AsyncioCursor 

### PR DESCRIPTION
**Pull request by EggieCode**
- [X] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

Fix the merge conflicts in #5354. This adds support for `async for` over AsyncioCursor.

### CODE REVIEW

**Comment by AtnNn** [comment]
This looks like a duplicate of #5354. Is there any reason for opening a new pull request? The same merge conflict seems to be present, and these aren't your commits.

**Comment by EggieCode** [comment]
@AtnNn Because #5354 has a merge conflict for more a half year.
And need to me resolved for asyncio issues with python 3.4 or higher.

**Comment by AtnNn** [comment]
@EggieCode Github still complains that "This branch cannot be rebased due to conflicts".

Pinging @dalanmiller @tryneus. Were there any unresolved issues with this branch?

**Comment by EggieCode** [comment]
Stange: http://imgur.com/cttiO6c

**Comment by dalanmiller** [comment]
I'll check later and try to merge this in if there are no conflicts.

**Comment by dalanmiller** [comment]
Also thank you to @eggiecode for fixing the conflict!

**Comment by EggieCode** [comment]
No problem!

**Pull request merged**
