### PR TITLE
Fix for https://github.com/rethinkdb/rethinkdb/issues/4061

### PR DESCRIPTION
**Pull request by damonmcminn**

### CODE REVIEW

**Comment by danielmewes** [comment]
Thank you for the pull request @damonmcminn.

If you haven't done so yet, would you mind signing our contributor agreement at http://rethinkdb.com/community/cla/ ? We require this for legal reasons before merging pull requests.

@Tryneus can you take a look at this change please?

**Comment by damonmcminn** [comment]
No problem @danielmewes!

Have signed the CLA.

Fix works on assumption that version is in form `rethinkdb x.x.x`.

**Comment by Tryneus** [comment]
Hmm...this was fixed in `v1.16.x` in commit 342b8e4b, but I guess that was never put into `next`, so it showed up again in `v2.0.x`.  Anyway, this is identical, so looks good!  Thanks for the help, @damonmcminn!

**Comment by Tryneus** [comment]
Ok, merged into `next` and cherry-picked into `v2.0.x` in commit 95d8188.

**Comment by damonmcminn** [comment]
Brilliant! Thanks chaps.

**Pull request merged**
