### PR TITLE
Added version var to Python Driver

### PR DESCRIPTION
**Pull request by yograterol**
QuickFix https://github.com/rethinkdb/rethinkdb/issues/3100

### CODE REVIEW

**Comment by danielmewes** [comment]
Hi @yograterol, thank you for your pull request!

This solution isn't very practical unfortunately since it requires manual updating for every new version.
What we need is something similar to this line from the web UI makefile https://github.com/rethinkdb/rethinkdb/blob/next/mk/webui.mk#L89 that injects the RethinkDB version as part of the make process.

Have you signed our CLA http://rethinkdb.com/community/cla/ yet? We'll need that before we can merge a pull request.

**Comment by AtnNn** [comment]
Having  `r.__version__` would be great, but as @danielmewes says, the version is already specified elsewhere. In this case, it's in `setup.py`.

Perhaps you could do something like put `__version__ = "1.16.0-0"` in `rethinkdb/version.py`, using `execfile` to access it from `setup.py` and `import` to access it from `__init__.py`

**Comment by AtnNn** [comment]
PEP 396 mentions having a `setup.cfg` file with a `version-from-file` field. I wonder if that would work.

**Comment by yograterol** [comment]
@danielmewes @AtnNn You are right, well I can do version.py and setup.cfg, It can be use with automatic rethinkdb build. 

BTW, I will sing the CLA.

**Comment by yograterol** [comment]
@danielmewes @AtnNn I did a change for use the version from setup, but exist a solution with metadata https://github.com/openstack-dev/pbr.

**Comment by AtnNn** [comment]
@yograterol I would prefer not introducing a dependency on setuptools or pbr.

**Comment by yograterol** [comment]
@AtnNn ok, here you go my changes

**Comment by AtnNn** [comment]
@yograterol this change depends on setuptools.

**Comment by yograterol** [comment]
Close this PR, in the rebase get changes than I don't want.

**Pull request closed without merging**
