### PR TITLE
[WIP] Port RethinkDB web interface to ES6

### PR DESCRIPTION
**Pull request by kvz**
Hey there, there's been some talk on #open-rethinkdb that it would be a good idea to port the web interface from CoffeeScript to ES6. I have recently released a [tool](https://github.com/kvz/invig) that helps with this, and I decided to run it on the webui.

Having read the `README.md` it wasn't immediately apparent to me  how to run the project locally, so that should tell you what stage this is in: a work in progress and by no means ready to be merged ⚠️ . 
I just thought I'd submit it already so it is known we can automate most of this, and focus our discussion/efforts.

Todos

- [x] Port Gulp to npm run scripts
- [ ] Run (tests) and hammer out issues
- [ ] Fix all remaining eslint issues:

screen shot 2017-02-15 at 10 54 56

### CODE REVIEW

**Comment by AtnNn** [comment]
Thanks doing this. There's been a lot of talk about moving to ES6 but this is the first attempt I've seen.

Note to others: this does not build. `gulp` does not terminate.

**Comment by kvz** [comment]
Correct, this is a raw code port so far. There is talk on slack in #webui about the next steps to take (perhaps using the standalone webui that uses npm scripts as a base for the port)

**Comment by AtnNn** [comment]
@kvz I just put my changes up here https://github.com/rethinkdb/rethinkdb/pull/6344

**Comment by kvz** [comment]
Excellent! I'll keep following that PR and see when it lands, then redo my work here.

**Comment by kvz** [comment]
Okay as a quick headsup: https://github.com/rethinkdb/rethinkdb/pull/6344 was merged so I'll get the new webui to work on my machine, and then redo the work that was pending in this PR in a new one. Closing this one for now.

**Comment by kvz** [comment]
I was looking to work on this today, but after checking out things locally I noticed a gulp-based build architecture. Upon investigation I found:

```
commit caf72d78abc6e932729d8e6d05a434b45c9f7ea6
Author: Sam Hughes <sam@samuelhughes.com>
Date:   Fri May 12 13:34:32 2017 -0700

    Reverts web ui changes that break the build.

    Revert "add missing shebang"
    This reverts commit 7c28c93abb10c45adc4d255b8d7ab10b9e6d5bc8.

    Revert "wrap the npm binary to use the correct node.js"
    This reverts commit d64516c5d77d71679915cb0f69b57ba009d34eb3.

    Revert "Merge branch 'webui' into 'next'"
    This reverts commit 3710301531a78d6dd867d14fe7631a6b6b3c1f26, reversing
    changes made to 44a4e32a857022a3b1627d16cf43746eae456b0b.
```

Am I correct to conclude that work I need to base the es6 port on has been reverted and I'm to wait a bit longer?

**Comment by AtnNn** [comment]
@kvz feel free to checkout the commit before the revert and base your changes on that.

I'll push those changes back as soon as I fix some of the build issues they caused. However building the stand-alone web UI with `npm` works fine.

**Comment by kvz** [comment]
Thanks @AtnNn! Since I already jumped the gun earlier and am scared of doing three ports (or running into subtle merge conflicts), I'd feel safer committing to another run once the dust has settled in master a bit, hope you understand! 😸

**Pull request closed without merging**
