### PR TITLE
Backport 'Treat release_superblock properly in do_read' to 2.3.x

### PR DESCRIPTION
**Pull request by tommilligan**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description

The PR backports the fix described in https://github.com/rethinkdb/rethinkdb/pull/6710 to the 2.3.x branch, to attempt mitigation of https://github.com/rethinkdb/rethinkdb/issues/6863

### CODE REVIEW

**Comment by gabor-boros** [comment]
@tommilligan why would you like to backport that change to 2.3.x instead of using 2.4?

**Comment by tommilligan** [comment]
It's a fair point - we have investigated upgrading to 2.4, but as it requires data file migrations, it wouldn't be a reversible upgrade for us. It's also just not a high priority for us at the moment. As there has been considerable work on the `next` branch since the 2.4 release, we're thinking of waiting for a point release unless we have a really good reason to upgrade.

FWIW we've been running this patch in production since I opened the PR, and haven't seen any issues (although this is a non-reproducible bug, so :shrug:).

**Comment by gabor-boros** [comment]
@srh if you agree we could merge this

**Comment by srh** [comment]
Please never hesitate to ping me multiple times if I don't respond.

Merging.

**Pull request merged**
