### PR TITLE
Fix typos in 2.3.6 Release Notes

### PR DESCRIPTION
**Pull request by chrisvariety**
The formatting of Server/Packaging sections did not render properly in GitHub Markdown.

Additionally, I'm assuming the improved compatibility for Chrome was indeed Chrome 58, which was very recently released, and not Chrome 48, which was released Jan 2016.

- [x] I have read and agreed to the RethinkDB Contributor License Agreement (the latest one!) http://rethinkdb.com/community/cla/

### CODE REVIEW

**Comment by chrisvariety** [comment]
View rendered output here: https://github.com/chrisvariety/rethinkdb/blob/9e9a197aba41614a763654134d087efed960b728/NOTES.md

**Comment by AtnNn** [comment]
`NOTES.md` contains nested lists indented a single space going all the way back to rethinkdb 2.1. I wonder how long they haven't been rendering correctly. I believe a better fix would be to indent them two spaces instead of one like it was done before 2.1.

The linked issue (#5300) mentions chrome 49 and 50, not 58.

**Comment by chrisvariety** [comment]
Yes, it does look like perhaps #5300 just took quite a while to land, my mistake. I've updated the pull to reflect Chrome 49 instead.

I've also updated formatting going back to 2.1, with two spaces for sublists as per your suggestion.

**Comment by AtnNn** [comment]
Thanks!

**Pull request merged**
