### PR TITLE
Websocket transport for the Javascript driver

### PR DESCRIPTION
**Pull request by dparnell**
Hi, I've been playing with alternate ways of connecting to a rethinkdb database and have built something that allows a web page to connect to a rethinkdb database via a websocket connection.
I've been using it in a simple internal app for some time now and it seems to be working very well for my needs :smile: 
Thanks for rethinkdb, it's awesome

Daniel

### CODE REVIEW

**Comment by danielmewes** [comment]
Hey @dparnell, nice patch. Thank you for the pull request.

I think we are not going to merge this into the main driver for now, because we won't be using it in our web UI and wouldn't have a great way for testing it and making sure that the code keeps working. I hope you understand.

That being said we have thought about switching the web UI to websockets (https://github.com/rethinkdb/rethinkdb/issues/3510), and if we end up doing that, your patches might become useful for the main driver.
Another change in our main server that would make this really useful would be adding user authentication and additional security https://github.com/rethinkdb/rethinkdb/issues/218 . At that point it will become feasible to connect directly from the browser to a database for a larger group of users, and websockets would likely be the way to go about that.

I think for the time being we won't make this part of the main driver, but I'll keep the pull request open nonetheless. Hope that's ok with you.
Do you have any plans of publishing your changes separately? I'm sure there will be a few people who are interested in this.

**Comment by dparnell** [comment]
Thanks, I wondered if that might be the case.  I'm also working on adding the ability to authenticate via a web page.  The idea I'm working on at the moment is to have a proxy that sits in front of the rethinkdb server that uses a provided auth token to determine the user logging in.  This is then used to get the privs that should be granted to the user and so any query that comes in is augmented/checked to ensure the user has the necessary privs on the desired tables.

**Comment by danielmewes** [comment]
@dparnell That sounds like a really interesting project. Are you planning to open source it?

**Comment by dparnell** [comment]
Possibly, it's written in Erlang at the moment which does limit the number of potential developers, but once there is a reference implementation porting it to another language wouldn't be too tricky.  The other thing I'm working on at the moment is some new functions in ReQL to materialize a subselect to stop rethinkdb from re-evaluating it each time through a filter function.  I've got that part working and while it helped the query I'm trying to do it's still too slow so I'm looking at trying to make a new function that sorts a given array so that the `contains` function can use a binary chop search instead of a linear search.  It's been fun digging through the guts of the rethinkdb codebase :smile:

**Comment by srh** [comment]
Closing this.  Why now?  This is in preparation for `v2.4.x` becoming the main RethinkDB branch instead of `next`.

Also note:
- This PR was made before the Apache 2.0 relicensing, so right now its contents could be presumed AGPLv3-licensed, unless we know its author signed the RethinkDB CLA before the company folded.

- The JavaScript driver is now located in https://github.com/rethinkdb/rethinkdb-javascript

- It seems like it could be useful to somebody, which is why the PR had been left open.

**Comment by dparnell** [comment]
I don't recall signing the RethingDB CLA, however I'm happy for this code to be used in any way.

**Pull request closed without merging**
