### PR TITLE
added a as_json method to deal with bitop appearances in Rails 3.2.13

### PR DESCRIPTION
**Pull request by ajose01**
This issue dealt with a similar item #2284 however it did not resolve for rails 3.2.13.

Added this small fix to deal with that.

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the PR @ajose01 !

If you haven't done so yet, would you mind signing our contributor agreement online? http://rethinkdb.com/community/cla/

@mlucy could you review please?

**Comment by ajose01** [comment]
@danielmewes I signed :)

**Comment by mlucy** [comment]
Looks good to me.  Thanks for the PR @ajose01 !

**Comment by ajose01** [comment]
awesome. thank you both for reviewing. @mlucy @danielmewes

**Comment by danielmewes** [comment]
Also picked into `v2.1.x` with 723c0193a5ddb5547317396e04db37c05bbda266

**Comment by danielmewes** [comment]
The fix was shipped with the RethinkDB 2.1.0.1 Ruby driver.

**Pull request merged**
