### PR TITLE
Fix Node.js v7 deprecation warning

### PR DESCRIPTION
**Pull request by aemino**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
This commit should fix the Buffer deprecation warning that occurs in Node.js v7, which is as follows: ```DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.```

It also attempts to ensure backwards-compatibility by using `Buffer.from` if present, while defaulting to `new Buffer` if `Buffer.from` is not available, which should allow the driver to remain backwards compatible for Node.js versions where `Buffer.from` was not yet implemented.

### CODE REVIEW

**Comment by chrisvariety** [comment]
LGTM!

You could consider using the "new" constructor when Buffer.from is not available, but I'm not entirely convinced there's any benefit in doing so.

You could also attempt to DRY it up a bit, but again not personally convinced doing so would introduce anything other than misdirection.

**Comment by Programmix** [comment]
I think you're right about using `new Buffer()`; I had the wrong idea that `new Buffer()` was a slightly more recent change to Node. Other than that, I don't think the code is too repetitive to the point where it deserves its own function or anything.

Thanks for your feedback!

**Comment by GusCaplan** [comment]
toString is a method not a property 👀

**Comment by Programmix** [comment]
Whoops! Thanks for pointing that out.

**Comment by chrisvariety** [comment]
Agreed LGTM.

gentle ping @deontologician @AtnNn would be good to get this in as Buffer without the constructor throws deprecation warnings in Node v6 which is an LTS release expected to last through 2018.

**Comment by AtnNn** [comment]
Does it work in all supported versions of `"node": ">= 0.10.0"`?

**Comment by GusCaplan** [comment]
this passed make in my local tests and ran on all symver major and minor versions of node.js

**Comment by Programmix** [comment]
All versions of `node >= 0.10.0` should work with the changes, as it is designed to be backwards compatible and use `new Buffer` if `Buffer.from` is not available (which it is not in Node < v6)

**Comment by marshall007** [comment]
@Programmix for the sake of clarity, I think we should use a polyfill here instead of doing those checks inline. [`node-buffer-v6-shim`](https://github.com/Daplie/node-buffer-v6-shim) seems like a good choice.

**Comment by chrisvariety** [comment]
@marshall007 As far as I can tell, the repository you linked to modifies Node itself globally. In other words, it modifies Buffer itself, and therefore the Buffer changes would apply globally to the whole application. It does not just modify Buffer for the rethinkdb package. To put it another way, it's not so much a polyfill as it is a monkeypatch. I would not recommend using that repository.

Additionally, the [existing dependencies](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/package.json#L17) are not extensive at all, and adding another dependency for a two line fix does not seem worth it to me, though I realize that may go against the overall "Node philosophy".

**Comment by marshall007** [comment]
@chrisvariety you're correct that it modifies the global `Buffer` object, but it does so in a "defensive" way and does not modify any pre-v6 Buffer APIs. It's also a complete no-op in v6+. I don't really see any harm in patching the global object in this particular case.

**Comment by marshall007** [comment]
If there are strong objections to patching the `Buffer` global, let's just move forward as-is. I would at least like to see the `new Buffer` vs `Buffer.from` logic pulled out into `utils.coffee` with a comment. Currently, the purpose of those lines is unclear unless you're already aware of the v6 deprecations.

Thoughts @chrisvariety and @Programmix?

**Comment by chrisvariety** [comment]
@marshall007 Sure, moving it out into `utils` adds a layer of indirection but would make intent clearer. Could go ether way.

As far as `Buffer` is concerned, I personally see no benefit in including an external lib but realize in the end probably it won't matter.

This pull removes a deprecation warning showing up in node v6 while being both forwards and backwards compatible, which is great and solves an immediate need, but honestly #3771 obviates all of this and is probably where efforts should be focused.

**Comment by Programmix** [comment]
@marshall007 @chrisvariety Absolutely agree that we should push to make rethinkdbdash the official driver.

Regarding what was suggested, I'm open to either using a shim or utils. However, I don't see too much of a problem with the current simple solution. I could add a comment explaining what's going on, if that would help.  I do see the point you make about clarity of the code though. Like Chris pointed out, in the end it most likely will not matter to the functionality.

**Comment by AtnNn** [comment]
This patch fails to build. Is a newer version of coffee script required? If so it should be added to `configure`.

```
drivers/javascript/net.coffee:1025:77: error: unexpected :
            buffer_message = (Buffer.from ? Buffer.from(message.toString()) : new Buffer(message.toString()))
```

Full log: http://thanos.atnnn.com/build/1407/log

**Comment by GusCaplan** [comment]
it should be
```coffeescript
if Buffer.from then Buffer.from(message.toString()) else new Buffer(message.toString())
```

**Comment by Programmix** [comment]
This should be fixed. I primarily use JavaScript; as such, I wasn't aware that CoffeeScript had altered ternary notation.

**Comment by marshall007** [comment]
LGTM

**Comment by lenovouser** [comment]
LGTM

**Comment by srh** [comment]
Closing and made issue https://github.com/rethinkdb/rethinkdb-javascript/issues/8 in the new javascript driver repository.  I intend to revisit this after v2.4.2 gets released.

**Pull request closed without merging**
