### PR TITLE
Add support for ARM64/AARCH64

### LINKED ISSUE #5265: Support 64 bit ARM architecture
Related to https://github.com/rethinkdb/rethinkdb/issues/5249

### PR DESCRIPTION
**Pull request by robertjpayne**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description

This adds the necessary assembly to support ARM64 and AARCH64. I need help getting tests setup on other platforms as I've primarily tested this assembly on an iPhone 6s.

This resolves #5265

### CODE REVIEW

**Comment by robertjpayne** [comment]
Also a massive shout out to @raedwulf for his help with the assembly!

**Comment by AtnNn** [comment]
Wonderful!

What is the difference between `__arm64__` and `__aarch64__`?

Your changes sometimes check only for one of those, sometimes for both.

**Comment by robertjpayne** [comment]
@AtnNn sorry I had missed one, as far as I know for the general assembly the instructions and ABI is the same -- the main difference between ARM64 and AARCH64 is on the fringe instructions.

Apple uses ARM64 on iOS and I'm unsure if other providers do or not while most 64-bit ARM linux servers use AARCH64

**Comment by gdeverlant** [comment]
This is what happens when I try to compile from your repo:

Based on tutorial at : https://rethinkdb.com/docs/build/

```
 ./configure --allow-fetch
* Detecting system configuration
Bash:                           4.3.30(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 6.4.0 (/usr/bin/c++)
Host System:                    aarch64-linux-gnu
Build System:                   Linux 4.12.0-gx-117136-g44bd33f aarch64
Cross-compiling:                no
Host Operating System:          Linux
* Error: unsupported architecture: aarch64-linux-gnu

* Aborting configure
```

**Comment by robertjpayne** [comment]
@gdeverlant I didn't update any of the build scripts so that may be what's causing the issue…

**Comment by gdeverlant** [comment]
After chaing the line **105** to this it compiles : 

```
    case "${MACHINE%%-*}" in
        x86_64|i?86)
            true ;;
        arm*|aarch*)
            var_append LDFLAGS -ldl
            final_warning="ARM support is still experimental" ;;
```

**Comment by gdeverlant** [comment]
```
$ make -j4
    [1/473] FETCH node_6.11.0
    [2/473] INSTALL-INCLUDE gtest_1.7.0
    [3/473] FETCH protobuf_2.5.0
    [4/473] FETCH re2_2015-11-01
    [5/473] FETCH v8_3.30.33.16-patched
    [6/473] FETCH boost_1.60.0
    [7/473] FETCH zlib_1.2.11
    [8/473] FETCH curl_7.54.1
    [9/473] FETCH openssl_1.0.2l
    [10/473] FETCH jemalloc_4.5.0
    [11/473] FETCH libidn_1.28
    [12/473] BUILD openssl_1.0.2l
    [13/473] CP build/release/rethinkdb-gdb.py
    [14/473] CONVERT_PROTOFILE build/drivers/ruby/lib/ql2.pb.rb
    [15/473] CONVERT_PROTOFILE drivers/ruby/lib/ql2.pb.rb
    [16/473] CP ./build/drivers/python/rethinkdb/
    [17/473] CONVERT_PROTOFILE build/drivers/python/rethinkdb/ql2_pb2.py
    [18/473] CONVERT_PROTOFILE drivers/python/rethinkdb/ql2_pb2.py
    [19/473] BUILD node_6.11.0
    [20/473] CONVERT_PROTOFILE build/drivers/javascript/proto-def.js
    [21/473] INSTALL-INCLUDE protobuf_2.5.0
    [22/473] INSTALL-INCLUDE re2_2015-11-01
    [23/473] INSTALL-INCLUDE v8_3.30.33.16-patched
    [24/473] INSTALL-INCLUDE zlib_1.2.11
    [25/473] INSTALL-INCLUDE curl_7.54.1
    [26/473] INSTALL-INCLUDE jemalloc_4.5.0
    [27/473] BUILD v8_3.30.33.16-patched
+ [[ /usr/bin/c++ = CLANG ]]
+ [[ /usr/bin/c++ = CLANG ]]
+ [[ Linux = Darwin ]]
+ arch_gypflags=
+ raspberry_pi_gypflags='-Darm_version=6 -Darm_fpu=vfpv2'
++ /usr/bin/c++ -dumpmachine
+ host=aarch64-linux-gnu
+ case ${host%%-*} in
+ arch=native
+ mode=release
+ [[ native = \s\3\9\0\x ]]
+ pkg_make native.release CXX=/usr/bin/c++ LINK=/usr/bin/c++ LINK.target=/usr/bin/c++ 'GYPFLAGS=-Dwerror= ' V=1
+ in_dir /mnt/virtual/compile/rethinkdb-arm64/build/external/v8_3.30.33.16-patched/build make native.release CXX=/usr/bin/c++ LINK=/usr/bin/c++ LINK.target=/usr/bin/c++ 'GYPFLAGS=-Dwerror= ' V=1
+ local dir=/mnt/virtual/compile/rethinkdb-arm64/build/external/v8_3.30.33.16-patched/build
+ shift
+ cd /mnt/virtual/compile/rethinkdb-arm64/build/external/v8_3.30.33.16-patched/build
+ make native.release CXX=/usr/bin/c++ LINK=/usr/bin/c++ LINK.target=/usr/bin/c++ 'GYPFLAGS=-Dwerror= ' V=1
make[2]: Entering directory '/mnt/virtual/compile/rethinkdb-arm64/build/external/v8_3.30.33.16-patched/build'
make[2]: *** No rule to make target 'native.release'.  Stop.
make[2]: Leaving directory '/mnt/virtual/compile/rethinkdb-arm64/build/external/v8_3.30.33.16-patched/build'

Full error log: ./build/external/v8_3.30.33.16-patched_install.log
mk/support/build.mk:148: recipe for target 'build/external/v8_3.30.33.16-patched/lib/libv8.a' failed
make[1]: *** [build/external/v8_3.30.33.16-patched/lib/libv8.a] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by robertjpayne** [comment]
@gdeverlant yea looks like more build script tweaks necessary… I have a totally separate build system in place at the moment for my iOS support (which is why I ported to ARM64 to begin with) that doesn't include v8…

**Comment by gdeverlant** [comment]
Have a look at the last comment with the log.

**Comment by robertjpayne** [comment]
@gdeverlant try latest commits, I'm just toying at this point I have no idea if this is what is necessary…

**Comment by gdeverlant** [comment]
Retrying again let's see if this goes well !

**Comment by robertjpayne** [comment]
@gdeverlant you in the slack channel might be easier to fix/do this over DM...

**Comment by gdeverlant** [comment]
Ok I'm coming

**Comment by gdeverlant** [comment]
I think we need to find the equivalent for **'GYPFLAGS=-Dwerror= -Darm_version=6 -Darm_fpu=vfpv2'** for aarch64 and arm64.

arm_gypflags='-Darm_version=6 -Darm_fpu=vfpv2'

are only good for armv6,armv7 and armv5 I think

for arm64 or aarch64 the following should be : 

-Darm_version=8

-Darm_fpu=we need to find the value of this. We need to find the Floating Point Unit which are available.

**Comment by gdeverlant** [comment]
This is something which help us : https://groups.google.com/forum/#!topic/v8-users/9Pp6csasgMo

**Comment by gdeverlant** [comment]
For Google Protobuffer I found a patch that might be important to integrate 👍 

https://gist.github.com/BennettSmith/7111094#file-0001-add-generic-gcc-support-for-atomic-operations-patch

**Comment by robertjpayne** [comment]
I think it's going to be an issue with v8 more than anything?

**Comment by AtnNn** [comment]
Perhaps base your changes off of #6401

**Comment by srh** [comment]
Hey @robertjpayne, can I merge this?  (Should I?)

My guess is, if it's not working everywhere, it's still harmless and works some places, right?

**Comment by robertjpayne** [comment]
The main issue was v8 working on arm64, I don't really have any time left to try and tidy this up but it should be mergable into #6401 easily? And yea it's all `#if` wraps so should be pretty harmless.

**Comment by srh** [comment]
I guess I could disable JS and merge.

**Comment by srh** [comment]
Alright, I just merged and pushed.  In next as of 433cbe7c7a6714e57ec1f999c0b7f81157005775.

Thanks!

**Comment by srh** [comment]
The change is now cherry-picked to the v2.4.x branch, too. fc0ca2eb504c4caf5a1b43c619580ce58116a79c

**Pull request closed without merging**
