### PR TITLE
Gevent support updated with (some tests)

### PR DESCRIPTION
**Pull request by thedrow**
I merged from next and copy/pasted the tornado tests (with adjustments of course) but there are still TODOs in there because there are some tests I don't know how to rewrite to gevent.
I can't seem to run the tests so you'll have to excuse me if something isn't working properly.
I hope you guys can merge this and do the rest.

### CODE REVIEW

**Comment by thedrow** [comment]
Something went wrong during the merge...

**Comment by danielmewes** [comment]
Thanks for your work on this @thedrow !

Maybe you can create a separate branch which is only `rethinkdb:grey_python_gevent` with `next` merged into it, and then merge that into your branch and diff your branch against that one?
That way the diff should only contain the changes you've made.

Also pinging @Tryneus .

**Comment by Tryneus** [comment]
@thedrow - this pull request is unfortunately a little out of hand - my apologies that the `grey_python_gevent` branch was so out-of-date.  I've pushed my latest version of the branch, which has been merged with `next` as of today, and includes running tests.  If you have any changes or fixes to the latest version of that branch, I'd be happy to review any pull requests.

Thanks for the help, @thedrow!

**Comment by thedrow** [comment]
I had (partial) tests in there. I'll try to set up a PR as soon as possible.

**Pull request closed without merging**
