### PR TITLE
Use GCC 5 on Yakkety

### LINKED ISSUE #6172: Cannot Install RethinkDB using Binaries on Ubuntu 16.10
After doing the following command:

```bash
source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
```

I make an update and I got error:
```bash
Err:8 http://download.rethinkdb.com/apt yakkety/main amd64 Packages            
  404  Not Found
...
...
...
Fetched 93.3 kB in 12s (7,632 B/s)                                             
Reading package lists... Done
W: The repository 'http://download.rethinkdb.com/apt yakkety Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://download.rethinkdb.com/apt/dists/yakkety/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
casper@casper-Z97X-UD3H:~$ sudo apt-get -y install rethinkdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rethinkdb
```

How can I solve this problem?

### PR DESCRIPTION
**Pull request by AtnNn**
Fixes #6172 in `v2.3.x`

- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### CODE REVIEW

**Comment by srh** [comment]
I'm going to look at this.  I got a different error on Yakkety than what was reported there.

**Comment by srh** [comment]
Okay, looks okay to me.

**Comment by AtnNn** [comment]
Also merged into 2.4.x as fb2b7ce

**Comment by srh** [comment]
Whoa, hold on, in 2.4.x?

**Pull request merged**
