### PR TITLE
fix jemalloc for systems with /lib64 library paths

### PR DESCRIPTION
**Pull request by mbains**
Partial fix for #2363

### CODE REVIEW

**Comment by mbains** [comment]
I went ahead and added the protobuf fix too. 
Builds ok on my opensuse 13.2 64bit. 

I did not get a chance to test these on other systems.

**Comment by danielmewes** [comment]
Thanks for the PR @mbains !

Have you signed out CLA? If not, you can do so online: http://rethinkdb.com/community/cla/

@AtnNn can you take a look at this please?

**Comment by AtnNn** [comment]
Thanks @mbains. This looks good to me, but I want to test it on other platforms before merging it.

**Comment by mbains** [comment]
@danielmewes Yes, I signed the CLA. 

Thanks

**Comment by danielmewes** [comment]
Sorry for the delay @mbains . We will try to test this soon and then hopefully merge it.

**Comment by danielmewes** [comment]
Running a test built now.

**Comment by danielmewes** [comment]
Ok this looks good. Thanks again for the patch @mbains .

**Comment by danielmewes** [comment]
Cherry-picked into v2.3.x via 9a2067a.

**Pull request merged**
