### PR TITLE
Don't print an error if the socket is closed.

### PR DESCRIPTION
**Pull request by danielmewes**
This can happen as part of a normal conn.close() call.

@deontologician @pires

### CODE REVIEW

**Comment by danielmewes** [comment]
Hmm maybe we should still add an `exec.awaitTermination` to `close()` after it has closed the socket?

**Comment by deontologician** [comment]
Actually, yeah, that seems sensible. If it doesn't finish we know there's something we're missing

**Comment by pires** [comment]
Ah, good call! LGTM.

**Comment by danielmewes** [comment]
It's missing an exception handler:
```
/home/ssd3/daniel/rethinkdb/drivers/java/src/main/java/com/rethinkdb/net/Connection.java:201: error: unreported exception InterruptedException; must be caught or declared to be thrown
            if (exec != null && !exec.awaitTermination(60, TimeUnit.SECONDS)) {
```
We should probably print a warning if we get interrupted.

**Comment by danielmewes** [comment]
... or actually the right thing to do might be passing the interruptedException on and adding it to the `close()` signature?

**Comment by danielmewes** [comment]
Do we have other API functions that handle thread interruptions? How are we handling interrupted exceptions there?

**Comment by pires** [comment]
@danielmewes I thinks only the `responsePump` should deal with execution interruption. It's just one thread btw since `exec = Executors.newSingleThreadExecutor()` so it shouldn't be dramatic to pass the exception to `close()`.

**Comment by bchavez** [comment]
A bit of caution of the bug here https://github.com/rethinkdb/rethinkdb/issues/5448

Also, I'm not sure how safe it is in Java for the executor thread to `.close` on itself since the pump can call `.close` (on exception) then `exec.awaitTermination(60, TimeUnit.SECONDS)`? Would it await on itself for termination? I dunno about this, seems a bit twisty for me.

Lo, I've a subtle fondness for https://github.com/rethinkdb/rethinkdb/issues/5380 and pushing all the awaiter mechanics down a lower level into `SocketWrapper` (or renamed to something else) like the C#/.NET driver. Just my feeling when *connection mechanics* (awaiter stuffs) are at a lower level, there is a **clearer** *separation of concerns* between a logical connection object and the underlying connection mechanics.

**Comment by danielmewes** [comment]
Superseded by https://github.com/rethinkdb/rethinkdb/pull/5449

**Pull request closed without merging**
