### PR TITLE
Link to the Rust driver

### PR DESCRIPTION
**Pull request by rushmorem**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### CODE REVIEW

**Comment by AtnNn** [comment]
Thanks @rushmorem!

It would be nice to add a link to it here too:

https://rethinkdb.com/docs/install-drivers/
https://github.com/rethinkdb/docs/blob/master/0-getting-started/drivers/index.md

Could you please fill in the form at the bottom of the CLA?

**Comment by rushmorem** [comment]
> It would be nice to add a link to it here too

Yeah. I plan to do that. Thanks.

> Could you please fill in the form at the bottom of the CLA?

Now done. Thanks again. I thought I had already done that previously when I submitted a pull request to https://github.com/rethinkdb/docs...

**Comment by AtnNn** [comment]
Thanks!

**Comment by rushmorem** [comment]
> I plan to do that

[Now done](https://github.com/rethinkdb/docs/pull/1204).

**Pull request merged**
