### PR TITLE
Fixes #5980 - Java Driver: Remove Cursor from cursorCache on close()

### LINKED ISSUE #5980: Possible memory leak in Java driver when reusing a Connection
When only one connection is kept open and reused multiple times the `cursorCache` map is growing and the `Cursor` objects are never removed from it.

### PR DESCRIPTION
**Pull request by bchavez**
Compliments of the C# driver. :bow:

To Java driver, From the C# driver, with love. :heart: 

Reference https://github.com/rethinkdb/rethinkdb/issues/5980

----

:sparkles: :point_left: [***"Hey, hey, do that brand new thing... Uh-huh, Uh-huh!"***](https://www.youtube.com/watch?v=AltMeuPkWRs)

### CODE REVIEW

**Comment by azabujuban** [comment]
We tried the fix and it seems to have fixed the leak

**Comment by deontologician** [comment]
Ok, will get this merged today :+1:

**Comment by deontologician** [comment]
:+1: lgtm, merging

**Comment by deontologician** [comment]
Also on 2.3.x as well

**Pull request merged**
