### PR TITLE
add ssl support to python asyncio

### PR DESCRIPTION
**Pull request by mgwilliams**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
Adds SSL support to the asyncio python driver.

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the pull request @mgwilliams !

@Tryneus or @larkost could one of you grab this for review please?

**Comment by larkost** [comment]
I am working on testing for this now.

**Comment by larkost** [comment]
I completed the tests, and this is working as expected, so looks good. I did make a pair of changes in it in my branch:
- updated the copyright string to reflect that we are working on it in 2016
- got rid of the use of `kwargs` and the splat of that, replacing it by using the `ssl` arg directly and just setting it to `None` when appropriate. This is more readable in my opinion.

So once we are through review (CR 3738) I will merge this in from my branch (larkost/5921-asyncio-ssl-support), but credit you (@mgwilliams) for the changes in the notes.

**Comment by larkost** [comment]
This has been merged into `next` with cbcafbb8. Thank you @mgwilliams for contributing the basis of this change!

**Pull request closed without merging**
