### PR TITLE
Let Util.java::convertToPojo can convert db data to Enum, OffsetDateT…

### PR DESCRIPTION
**Pull request by QianJin2013**
…ime, BigDecimal, BigInteger, Double, Float, Boolean, Integer, Long, Short, Byte

Hi all, thank you for your great work.

Currently, Util.java::convertToPojo can NOT convert db data to any of the following types:
```
Enum, OffsetDateTime, BigDecimal, BigInteger, Double, Float, Boolean, Integer, Long, Short, Byte
```
Unfortunately, I am working on a project which have to convert db data to a Bean which in turn contains above types. 
Basically i do the convertion by following code: 
```
//Object SOME_TABLE_ROW_FROM_CURSOR = r.db.........getAll(...........;
com.rethinkdb.net.Util.convertToPojo.convertToPojo(SOME_TABLE_ROW_FROM_CURSOR, Optional.of(SOME_BEAN_CLASS.class))
```
where SOME_BEAN_CLASS is just a normal bean class, e.x:
```
public class SOME_BEAN_CLASS   {
    
  public enum StatusEnum {
    CREATED("opened"),
    MODIFIED("modified"),
    CLOSED("closed"),

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return value;
    }
  }

  private StatusEnum status = null;

  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  private OffsetDateTime createdAt = null;

  @JsonProperty("createdAt")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }
  
  @JsonProperty("someOtherBean")
  public SomeOtherBean> getSomeOtherBean() {
    return someOtherBean;
  }
  public void setSomeOtherBean(SomeOtherBean someOtherBean) {
    this.someOtherBean = someOtherBean;
  }

  @Override
  public boolean equals(Object o) {
    ...
  }

  @Override
  public int hashCode() {
    ...
  }

  @Override
  public String toString()  {
    ...
  }
}
```

This is very incomvenient, so i modified Util.java, hope you can merge it.

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the PR @QianJin2013!

Have you read and signed our CLA yet? http://rethinkdb.com/community/cla/

Pinging @deontologician for review.

I think we should make sure that the conversion throws something if the number received from RethinkDB isn't losslessly convertible to the target type (e.g. if it's too large for a Short, or if it's not an integer and we try to convert it to an Integer).

**Comment by deontologician** [comment]
@QianJin2013 would you mind adding some tests? You can model it after some of the other pojo test code here: https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/test/java/com/rethinkdb/RethinkDBTest.java#L266

**Comment by QianJin2013** [comment]
@deontologician OK, I'v been working on the test cases.

**Comment by QianJin2013** [comment]
@danielmewes OK, i will try the CLA as soon as i complete all test cases.
There are just ClassCastException throwed.
I'v found more types can not be handled.

**Comment by QianJin2013** [comment]
Hi, i have added test case and modified more type conversion logic and make pull request at https://github.com/rethinkdb/rethinkdb/pull/5484.
I am sorry, i do not know how to make pull request separately for each modification, i tried to rollback and start make new pull request for new modification, but the later modification still be appended to same pull request.

As a result, please ignore this pull request, and goto https://github.com/rethinkdb/rethinkdb/pull/5484

**Pull request closed without merging**
