### PR TITLE
[JS] support for ssl encryption and CA verification

### PR DESCRIPTION
**Pull request by jipperinbham**
[Addresses JavaScript Driver](https://github.com/rethinkdb/rethinkdb/issues/3158)

The following will use `tls.connect` when doing an SSL connection to a cluster. In order for this to be used, you'd need a proxy (Haproxy, nginx, etc) sitting in front of the RethinkDB cluster performing the SSL verification.

For now, the SSL support is only good for encrypting traffic and verifying the CA certification to prevent MITM attacks. 

For the implementation, I'm using additional `r.connect` options: `ssl` and `sslCaCerts` so a connection would look like the following:

```javascript
r.connect({ host: 'localhost',
            port: 28015,
            db: 'marvel',
            authKey: 'hunter2' },
            ssl: true,
            sslCaCerts: '/path/to/ca.crt'
          function(err, conn) { ... })
```

### CODE REVIEW

**Comment by danielmewes** [comment]
Nice, number three :)
@deontologician could you take a look at this patch?

(Also for consistency I think we should do the same with the `ssl` optional argument as for the Ruby driver, https://github.com/rethinkdb/rethinkdb/pull/4075#issuecomment-94173834 .)

**Comment by jipperinbham** [comment]
@danielmewes updated `ssl` arguments here as well.

**Comment by deontologician** [comment]
This looks good code-wise, it's not a lot of code and it sends the right stuff to the tls api. How do we check if it can make the connection? Do you need an SSL proxy?

**Comment by danielmewes** [comment]
@neumino mentioned on another thread (https://github.com/rethinkdb/rethinkdb/issues/4074#issuecomment-94611591):
> the proposed implementation uses readFileSync, which is pretty bad since it will block your whole node.js server the time to load the certificate.

I think we should replace it by an asynchronous method if possible.

**Comment by danielmewes** [comment]
He also suggested that we might want to cache the certificate file somewhere, so we don't have to go to the operating system for re-reading it for every new connection.

**Comment by joaojeronimo** [comment]
IMHO that would be over-optimization, how many times are we opening connections to rethinkdb for that to become a problem because of readFileSync ?

Also, why not follow the same signature of [tls.connect](https://nodejs.org/api/tls.html#tls_tls_connect_port_host_options_callback) and accept an options object that will be passed all the way to tls.connect (because it's what will be used underneath right ?) ? The options object is an object that may have `ca` and `cert` parameters that may be strings or buffers, so we pass on to the user the option of how to obtain those (they decide to use fs.readFile or fs.readFileSync). It would be a lot cleaner IMHO, [it's about 10 SLOC](https://github.com/joaojeronimo/rethinkdbdash/blob/master/lib/connection.js#L41).

**Comment by jipperinbham** [comment]
I agree that trying to optimize `readFileSync` is not necessary and connections should be reused not constantly opened/closed.

@joaojeronimo the connection options have been updated to look like:
```javascript
r.connect({ host: 'localhost',
            port: 28015,
            db: 'marvel',
            authKey: 'hunter2' },
            ssl:{
              caCerts: '/path/to/ca.crt'
            }
          function(err, conn) { ... })
```

So, if I'm understanding right, you'd want to just have the `ssl` hash accept the arguments `tls.connect`? And the example above would become:

```javascript
r.connect({ host: 'localhost',
            port: 28015,
            db: 'marvel',
            authKey: 'hunter2' },
            ssl:{
              ca: [ fs.readFileSync('/path/to/ca.crt') ]
            }
          function(err, conn) { ... })
```

**Comment by joaojeronimo** [comment]
Yes I think having the `ssl` hash be the same as the `options` hash used in `tls.connect` would be cleaner on the implementation (nothing else there to do, plus you support every option that tls.connect supports, which should be every possible option anyone would need), more idiomatic and node people would be a lot more familiar with how to use it.

**Comment by danielmewes** [comment]
I think accepting a file path for the certificate file like it does now is slightly nicer (and it makes it more consistent with the other drivers).

Would it be a big problem to change the file loading to `readFile`? From looking at the API it looks pretty straight forward (you could wrap it into a promise I think to avoid the separate callback, @deontologician could help you with that).

There are definitely a few users who open new connections very frequently, so I would prefer if the driver behaved well under that scenario.
@jipperinbham if you don't want to do this change don't worry. We can do it ourselves after the merge.

**Comment by jipperinbham** [comment]
@danielmewes I've made a [change](https://github.com/compose/rethinkdb/commit/1a80811a2911e492be03f8ca342fbdca3b4d2ac3) that I think is best given how different node is and the differences in how users may want to connect. It's what @joaojeronimo and I discussed above and it's also how my [PR](https://github.com/dancannon/gorethink/pull/179) to the gorethink driver is setup. 

Since the python and ruby drivers setup the SSL/TLS connection differently, I think it's ok to have the connect options differ slightly.

**Comment by danielmewes** [comment]
> Since the python and ruby drivers setup the SSL/TLS connection differently, I think it's ok to have the connect options differ slightly. 

I can live with that.

I'll leave the final review to @deontologician .

**Comment by deontologician** [comment]
Looks good, merged.

**Comment by joaojeronimo** [comment]
:+1: 

Is it going to be on npm right away or just released along with 2.1 ?

**Comment by danielmewes** [comment]
@joaojeronimo This will be released with the 2.1 release.

**Comment by joaojeronimo** [comment]
can't wait :smiley:

**Comment by pauliusuza** [comment]
Fix in PR #4786

**Pull request merged**
