### PR TITLE
Add an additional yield so _reader can close down

### PR DESCRIPTION
**Pull request by sontek**

### CODE REVIEW

**Comment by sontek** [comment]
@danielmewes @Tryneus This should fix #5043

**Comment by danielnelson** [comment]
Here is an alternative fix that doesn't rely on sleep:
```
diff --git a/drivers/python/rethinkdb/net_asyncio.py b/drivers/python/rethinkdb/net_asyncio.py
index f1d54f2..bb43f09 100644
--- a/drivers/python/rethinkdb/net_asyncio.py
+++ b/drivers/python/rethinkdb/net_asyncio.py
@@ -194,6 +194,7 @@ class ConnectionInstance(object):
             yield from self.run_query(noreply, False)
 
         self._streamwriter.close()
+        yield from self._reader_task
         return None
 
     @asyncio.coroutine
```

**Comment by sontek** [comment]
@danielnelson I like it :)

**Comment by sontek** [comment]
I rebased the changes to do @danielnelson's idea instead

**Comment by danielmewes** [comment]
Thanks for the PR! @Tryneus could you review this please?

**Comment by Tryneus** [comment]
Looks good!  Thanks for the help, @sontek and @danielnelson, sorry I didn't have time to look into this myself.

**Comment by Tryneus** [comment]
Cherry-picked the fix into `v2.2.x` in commit adbd608.

**Pull request merged**
