### PR TITLE
make json buffer and chunk size as argument parameters #4451

### PR DESCRIPTION
**Pull request by sebadiaz**
On a big file the buffer is not sufficient. I add argument parameter to change it.
I add too for the chunk size to accelerate import on big file

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the pull request, really appreciate it.

As mentioned in https://github.com/rethinkdb/rethinkdb/issues/4451#issuecomment-115360131 , I'd like to avoid exposing this option if possible. Let's see if @Tryneus has an idea.

On a different note: @sebadiaz have you signed our CLA yet? We require this for legal reasons before we can merge pull requests into the main code base. You can easily sign it online at http://rethinkdb.com/community/cla/ .

**Comment by Tryneus** [comment]
Please see my comment at https://github.com/rethinkdb/rethinkdb/issues/4451#issuecomment-115428306.

**Comment by sebadiaz** [comment]
The reason appear more clear on a big document when an arry is not finished we extend the file reading to continue on the array parsing
code extracted 
before_len = len(json_data) -> we take the size of the actual structure
to_read = max(json_read_chunk_size, before_len) -> we get this previous measure as max
json_data += file_in.read(min(to_read, json_max_buffer_size - before_len)) -> finally we use json_max_buffer_size - before_len because < to_read --> could be negative on non raising step(see next lines)

after reading we have
elif before_len == len(json_data) or len(json_data) >= json_max_buffer_size: --> this is the error , we can't raise on unfinished array 
                raise


Two solutions
  - set a big json_max_buffer_size with two solutions : 
	- fixed at starting
	- set to the file size
  - continue to read unless size limit exceed my new patch proposition in removing json_max_buffer_size
	except (ValueError, IndexError):
            before_len = len(json_data)
            to_read = max(json_read_chunk_size, before_len)
            json_data += file_in.read(to_read)
            if json_array and json_data[offset] == ",":
                offset = json.decoder.WHITESPACE.match(json_data, offset + 1).end()
            elif (not json_array) and before_len == len(json_data):
                break  # End of JSON
            elif before_len == len(json_data):
                raise
            progress_info[0].value = file_offset

**Comment by sebadiaz** [comment]
CLA is signed

**Comment by danielmewes** [comment]
Thanks for the update @sebadiaz . I like this better.
@Tryneus for what reasons do we have the `json_max_buffer_size` in the first place? Is it to avoid using too much memory if a JSON file is faulty or something else?

**Comment by Tryneus** [comment]
@danielmewes - yeah, the idea is that if a user provides the incorrect file or a JSON file with syntax errors, we don't want to go into swap or hit the OOM killer.  There's a chance this will happen even with the 128 MB limit (because we can import multiple tables in parallel), but that number was chosen because it is likely larger than any individual row that can be successfully imported (barring a JSON file with a high ratio of whitespace).

We would like to avoid the OOM killer because if the import is running on the same machine as the database server, there is a good chance the OOM killer will take out the server before the import process.

**Comment by danielmewes** [comment]
Hmm those are certainly valid concerns.
I think the problem might be JSON files that have indentation for each line. In that case the size of a document in the file can easily be a multiple of the actual document size. @sebadiaz is that actually the case in your input or are the whitespaces coming from something else?

Given this information, maybe a command line option like `--max-document-size` to set `json_max_buffer_size` as @sebadiaz had originally implemented isn't the worst idea. I'd prefer that name over `--change-max-buffer-size` since it's less cryptic.
@Tryneus do you think that would be fine?

I'd leave out the `read-chunk-size` flag though.

**Comment by Tryneus** [comment]
@danielmewes, that's reasonable, I would be ok with that.

**Comment by danielmewes** [comment]
Ok sounds good.

Sorry @sebadiaz for the back and forth. I'm going to add some comments on your first commit about the changes I think we need to do, and @Tryneus should probably do a quick pass as well. Thanks again for your help.

**Comment by sebadiaz** [comment]
Done. I hope to be the last round

**Comment by Tryneus** [comment]
Looks good, thanks for your patience, @sebadiaz!

**Comment by danielmewes** [comment]
Thank you @sebadiaz. @Tryneus do you want to push the button or should I?

**Comment by Tryneus** [comment]
@danielmewes - go ahead, technically I'm PTO today.

**Comment by danielmewes** [comment]
Merged :-)

**Pull request merged**
