### PR TITLE
Added `with` support for Cursor in python driver

### PR DESCRIPTION
**Pull request by yashmehrotra**
- [x] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
Added support for `with` statement in the python driver as mentioned in #5768. Now users will be able to run queries like:
```
with r.db('foo').table('bar').run(conn) as table:
     for row in table:
          pass
```

### CODE REVIEW

**Comment by danielmewes** [comment]
Thanks for the pull request @yashmehrotra !

Pinging @larkost

**Comment by larkost** [comment]
Looks good to me, but pinging @Tryneus to backstop me to confirm my thinking that there are no implications for versions like the AsyncIO backend.

**Comment by Tryneus** [comment]
Looks good to me, `cursor.close()` is non-blocking, anyway.  For this to work with `asyncio`, we would need `__aenter__` and `__aexit__` methods, but it shouldn't have any conflicts with this.

**Comment by larkost** [comment]
Ok, then I am merging this in. @yashmehrotra, thanks much for your submission!

**Comment by yashmehrotra** [comment]
@larkost Your Welcome. Happy to contribute :smile:

**Pull request merged**
