### PR TITLE
fix a few cross compilation issues

### PR DESCRIPTION
**Pull request by mbroadst**
/cc @AtnNn

### CODE REVIEW

**Comment by mbroadst** [comment]
ping

**Comment by danielmewes** [comment]
Thanks for the PR @mbroadst .

@larkost could you take a look at this when you have a bit of time?

**Comment by mbroadst** [comment]
hey guys, I actually have an amendment to this to reenable snapshotting but I'll need until tomorrow

**Comment by mbroadst** [comment]
@larkost hey I've updated the PR such that v8 snapshot is no longer disabled on cross compilation, so we're all good here afaict!

**Comment by larkost** [comment]
I have a couple of things on my plat before this, but I will try and get through my work on it soon. Thanks for the PR, and thanks for your patience.

**Comment by srh** [comment]
Hey @mbroadst I want to kill this PR by blindly trusting it's good and merging this.

But since you've been active I'll ask first.  Does it still sound like a good idea?  Should I merge it into v2.3.x as well as 2.4.x and next?

**Comment by mbroadst** [comment]
@srh yeah it should be fine still, the company I worked for at the time still builds rethinkdb as part of a yocro build with my fork that contains this patch. It's been in production for over a year

**Comment by srh** [comment]
In next as of commit f4621536ee3225f8bab7a2c124e39c85b1f0dc06
In v2.4.x as of commit 38cc16ca314a5ee52c42f654947e248d94b2bb45

**Pull request closed without merging**
