### PR TITLE
This fix solves the ambiguous message displayed by the logger

### PR DESCRIPTION
**Pull request by javierso**
- [ ] I have read and agreed to the RethinkDB Contributor License Agreement http://rethinkdb.com/community/cla/

### Description
<Please fill in the description of your pull request here. Thank you for your contribution!>

This fixes an ambiguous message on the log_writer module whenever it tries to write a message to a log file , but the log_write module hasn't yet being initialized with a proper  log file.

### CODE REVIEW

**Comment by javierso** [comment]
Forgot to mention the full history for this issue is capture on #3621.

**Comment by danielmewes** [comment]
Thanks for the PR @javierso . This looks correct.
Have you signed the CLA yet?

**Comment by javierso** [comment]
Yes I did sign the CLA and I left my contact info there:
Firs Name: Javier
Last Name : Sanchez

**Comment by danielmewes** [comment]
Thanks, merged.

**Pull request merged**
