### PR TITLE
Add mention of arrayLimit option and indexing to error message

### PR DESCRIPTION
**Pull request by t3hmrman**
Minimal fix to issue #3061 , Just added a message mentioning arrayLimit option and using an index.

### CODE REVIEW

**Comment by t3hmrman** [comment]
Not a substantial change, but would be great if someone looked over the prose -- figured I could at least knock this easy ticket out while I was visiting the office :smile:

**Comment by danielmewes** [comment]
Thanks @t3hmrman !
Would you mind signing our CLA http://rethinkdb.com/community/cla/ ? We require this before we can merge a pull request.

About the change itself: The option should be referred to as `array_limit` not `arrayLimit`. The camel case name is specific to the JavaScript driver (and maybe a few third part ones), while all of our drivers accept the underscore form `array_limit`. Other than that it looks good to me.

**Comment by danielmewes** [comment]
Oh also it should be "elements" instead of "documents" I think, since the array can for example be an array of numbers or strings.

**Comment by t3hmrman** [comment]
Hey @danielmewes , I just signed the CLA, and made the "elements" change! 

Also, the strings are kind of long -- is there a style guide?

**Comment by danielmewes** [comment]
Ah yes, good you mention it. We have an 89 character line length limit. Mind breaking the strings up?

**Comment by t3hmrman** [comment]
Just did some of the string splitting, but some tests are currently failing so looking into it (whether I caused them or not) -- would suggest not merging this in yet

**Comment by danielmewes** [comment]
@t3hmrman thanks. Which tests did you run? It's possible that some of them are testing for a specific error message and need to be adjusted.
The relevant ones are defined in `test/rql_test/src` and you can run them through the `test-runner` script in `test/rql_test`.

**Comment by t3hmrman** [comment]
Closing since I haven't worked on this in a super long time :<

**Pull request closed without merging**
