### PR TITLE
Add .swo to gitignore

### PR DESCRIPTION
**Pull request by aaronorosen**

### CODE REVIEW

**Comment by larkost** [comment]
For those (like me) who don't/didn't know; `.swo` (and `.swp, `.swn`, etc..) files are created when you open a file for editing in `vim`. The first concurrent editor makes a `.swp` file, and then they progressively march down the alphabet starting with `.swo`.

Personally I think that stuff like this belongs in your own `git` preferences, but we already have a `*.swp` entry, so there is precedent.

**Comment by aaronorosen** [comment]
I changed it to .sw? to ignore all the vim created files. I think having this here is helpful though I'm okay having it in my local git preferences.

**Comment by danielmewes** [comment]
`.sw?` sounds good to me.
Thanks for the PR @aaronorosen .

Have you already signed the CLA http://rethinkdb.com/community/cla/ ?

**Comment by aaronorosen** [comment]
yup i already have.

**Comment by danielmewes** [comment]
Thanks!

**Pull request merged**
