### PR TITLE
Java Driver: Fixing dbCreate() to run

### PR DESCRIPTION
**Pull request by bchavez**
Hi @deontologician. Shadowing your progress on your Java driver with my C# driver and I think we need run here. :)

https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver.Tests/ConnectionTest.cs

### CODE REVIEW

**Comment by danielmewes** [comment]
Pinging @deontologician

**Comment by danielmewes** [comment]
@bchavez had you signed our CLA before? (http://rethinkdb.com/community/cla/)

**Comment by bchavez** [comment]
Hi @danielmewes , I haven't, but I will right now.

**Comment by bchavez** [comment]
signed :+1: :)

**Comment by deontologician** [comment]
Ah thanks :) good catch. I'm rewriting the test structure now, but I would probably have copy/pasted this into the test template

**Pull request merged**
